# Generated by Django 4.1.7 on 2023-07-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_track_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='tag',
            field=models.ManyToManyField(blank=True, to='album.tag'),
        ),
    ]
